#Gradle
org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=1G
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true
org.gradle.parallel=true

#Kotlin
kotlin.daemon.jvmargs=-Xmx8G
kotlin.native.binary.gc=cms
kotlin.incremental.wasm=true
kotlin.apple.deprecated.allowUsingEmbedAndSignWithCocoaPodsDependencies=true
kotlin.mpp.enableCInteropCommonization=false
kotlin.mpp.enableCInteropCommonization.nowarn=true

#Android
android.useAndroidX=true
android.enableR8.fullMode=true
android.nonTransitiveRClass=true
