install! 'cocoapods', warn_for_unused_master_specs_repo: false

platform :ios, '15.0'
use_frameworks!

target 'iosApp' do
  pod 'FirebaseAuth'
  pod 'FirebaseCore'
  pod 'FirebaseFirestore'
  pod 'FirebaseMessaging'
  pod 'FirebaseRemoteConfig'
  pod 'GoogleSignIn'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
